env:
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
plugins:
  - prettier
root: true
rules:
  import/extensions: 'off'
  import/prefer-default-export: 'off'
  max-len: 'off'
  curly: 'error'
  object-curly-newline: 'off'
  operator-linebreak: 'off'
  prefer-arrow-callback: 'error'
  prettier/prettier: 'error'
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - err # Error decoration
        - obj # .reduce() object
        - pkg # Package instance
        - req
overrides:
  - files:
      - '**/__tests__/**'
      - '**/__mocks__/**'
      - '**/__helpers__/**'
      - '**/*.js'
    rules:
      import/no-extraneous-dependencies: 'off'
      no-console: 'off'
      no-param-reassign: 'off'
      strict: 'off'
